
services:
#  mongodb:
#    image: mongo
#    logging:
#      driver: none    
#    container_name: mongodb_torgi
#    ports:
#      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "***"
#      MONGO_INITDB_ROOT_PASSWORD: "***"
  
#    restart: always

  fastapi_app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - 443:443
      - 80:80
#   depends_on:
#     - mongodb
    restart: always